---
title: "My second Blog Post"
---

We should be able to look beyond ourselves and acknowledge
 the so called “forces of oppression “that are so “baked into everyone’s daily lives”. 

By benefiting from unearned advantages, specific groups have gained power and control over the laws, the media and the administrations that define today’s world. 
When thinking of Data science and its power, we can choose to use it to reinforce this system or to break it.

Systematic disadvantages have rendered oppressed groups invisible therefore vulnerable. As these groups are slowly emerging out of their anonymity, new and unknown, they are not welcomed with open arms. Instead they are met with hostility and fear. They are a threat to those who control the system because an equitable world would call for equal opportunities and chances for all. 

Oppressed groups are vulnerable because they are unwanted. They are vulnerable because the world has been built without them in mind, so they end up stumbling onto so many obstacles when going through diverse processes which the less disadvantaged groups seem to breeze through. 

Beyond the many groups that have been oppressed throughout history, there are those that arise from the intersections of two or more of them. These intersections bring up identities that are vulnerable to oppressive experience in ways that are new to all of us. 

For this reason, it is even more important to empathize with, feel for and listen to those around us. The lived experience will soon be too specific to be accessible to us. Soon, if not already now, we will need to develop the capacity to acknowledge others experience genuinely no matter how removed from them we are.
